SRC = main.c
.PHONY: arp_spoofing
all: arp_spoofing


arp_spoofing:
	gcc -o arp_spoofing arp_spoofing.c
# arp -a
# ip a, ip r

#	sudo arp-scan --interface=enp2s0 --localnet
#	sudo arp-scan --interface=enp0s3 --localnet
#	sudo ./arp_spoofing enp2s0 3c:7c:3f:c0:eb:83 0e:aa:a4:ec:90:16 a8:f9:4b:e5:62:b8 192.168.1.10 192.168.1.11 192.168.1.1  
		
